// Package orchestrator provides the central LLM orchestrator for coordinating JSON-RPC services.
package orchestrator

import (
	"time"
)

// WorkflowPlan represents a complete workflow plan generated by the LLM
type WorkflowPlan struct {
	ID          string                 `json:"id"`          // Unique workflow identifier
	Description string                 `json:"description"` // Human-readable description
	Steps       []WorkflowStep         `json:"steps"`       // Ordered steps to execute
	Context     map[string]interface{} `json:"context"`     // Shared context between steps
	CreatedAt   time.Time              `json:"created_at"`  // Creation timestamp
	Status      WorkflowStatus         `json:"status"`      // Current workflow status
}

// WorkflowStep represents a single step in a workflow
type WorkflowStep struct {
	ID          string                 `json:"id"`           // Unique step identifier
	Name        string                 `json:"name"`         // Step name
	Service     string                 `json:"service"`      // Target service name
	Method      string                 `json:"method"`       // JSON-RPC method to call
	Parameters  map[string]interface{} `json:"parameters"`   // Method parameters
	Inputs      []string               `json:"inputs"`       // Context variables to use as inputs
	Outputs     []string               `json:"outputs"`      // Output variables to store in context
	Condition   string                 `json:"condition"`    // Optional condition for execution
	RetryPolicy *RetryPolicy           `json:"retry_policy"` // Retry configuration
	Status      StepStatus             `json:"status"`       // Current step status
	Result      interface{}            `json:"result"`       // Step execution result
	Error       string                 `json:"error"`        // Error message if failed
	StartedAt   *time.Time             `json:"started_at"`   // When step started
	CompletedAt *time.Time             `json:"completed_at"` // When step completed
}

// WorkflowStatus represents the status of a workflow
type WorkflowStatus string

const (
	WorkflowStatusPending   WorkflowStatus = "pending"
	WorkflowStatusRunning   WorkflowStatus = "running"
	WorkflowStatusCompleted WorkflowStatus = "completed"
	WorkflowStatusFailed    WorkflowStatus = "failed"
	WorkflowStatusCancelled WorkflowStatus = "cancelled"
)

// StepStatus represents the status of a workflow step
type StepStatus string

const (
	StepStatusPending   StepStatus = "pending"
	StepStatusRunning   StepStatus = "running"
	StepStatusCompleted StepStatus = "completed"
	StepStatusFailed    StepStatus = "failed"
	StepStatusSkipped   StepStatus = "skipped"
)

// RetryPolicy defines retry behavior for a step
type RetryPolicy struct {
	MaxRetries int           `json:"max_retries"` // Maximum number of retries
	Delay      time.Duration `json:"delay"`       // Delay between retries
	Backoff    float64       `json:"backoff"`     // Exponential backoff multiplier
}

// ServiceCapability represents a service's capabilities discovered through introspection
type ServiceCapability struct {
	ServiceName  string            `json:"service_name"`  // Service identifier
	ServiceURL   string            `json:"service_url"`   // Service endpoint
	Description  string            `json:"description"`   // Service description
	Version      string            `json:"version"`       // Service version
	Methods      map[string]Method `json:"methods"`       // Available methods
	Capabilities []string          `json:"capabilities"`  // Service capabilities
	LastUpdated  time.Time         `json:"last_updated"`  // Last introspection time
	TTL          time.Duration     `json:"ttl"`           // Time to live for cache
	IsAvailable  bool              `json:"is_available"`  // Whether service is responding
	ResponseTime time.Duration     `json:"response_time"` // Last response time
}

// Method represents a JSON-RPC method with its metadata
type Method struct {
	Name        string      `json:"name"`        // Method name
	Description string      `json:"description"` // Method description
	Parameters  []Parameter `json:"parameters"`  // Method parameters
	Returns     string      `json:"returns"`     // Return type description
	Required    bool        `json:"required"`    // Whether method is required
}

// Parameter represents a method parameter
type Parameter struct {
	Name        string      `json:"name"`        // Parameter name
	Type        string      `json:"type"`        // Parameter type
	Description string      `json:"description"` // Parameter description
	Required    bool        `json:"required"`    // Whether parameter is required
	Default     interface{} `json:"default"`     // Default value if any
}

// OrchestratorConfig represents the orchestrator configuration
type OrchestratorConfig struct {
	LLMProvider      string        `json:"llm_provider"`      // LLM provider (gemini, openai, etc.)
	LLMAPIKey        string        `json:"llm_api_key"`       // LLM API key
	LLMModel         string        `json:"llm_model"`         // LLM model name
	ServiceURLs      []string      `json:"service_urls"`      // List of service URLs to introspect
	IntrospectionTTL time.Duration `json:"introspection_ttl"` // TTL for service capabilities cache
	MaxConcurrency   int           `json:"max_concurrency"`   // Maximum concurrent operations
	RequestTimeout   time.Duration `json:"request_timeout"`   // Default request timeout
	EnableLogging    bool          `json:"enable_logging"`    // Enable detailed logging
}

// UserRequest represents a user's natural language request
type UserRequest struct {
	ID        string                 `json:"id"`        // Unique request identifier
	UserID    string                 `json:"user_id"`   // User identifier
	Message   string                 `json:"message"`   // Natural language message
	Context   map[string]interface{} `json:"context"`   // Additional context
	Timestamp time.Time              `json:"timestamp"` // Request timestamp
}

// OrchestratorResponse represents the orchestrator's response
type OrchestratorResponse struct {
	RequestID  string                 `json:"request_id"`  // Original request ID
	WorkflowID string                 `json:"workflow_id"` // Generated workflow ID
	Response   string                 `json:"response"`    // Human-readable response
	Result     interface{}            `json:"result"`      // Structured result data
	Steps      []WorkflowStep         `json:"steps"`       // Executed steps
	Context    map[string]interface{} `json:"context"`     // Final context
	Success    bool                   `json:"success"`     // Whether execution was successful
	Error      string                 `json:"error"`       // Error message if failed
	Duration   time.Duration          `json:"duration"`    // Total execution time
	Timestamp  time.Time              `json:"timestamp"`   // Response timestamp
}

// IntrospectionResult represents the result of service introspection
type IntrospectionResult struct {
	Services   []ServiceCapability `json:"services"`    // Discovered services
	TotalFound int                 `json:"total_found"` // Total services found
	FailedURLs []string            `json:"failed_urls"` // URLs that failed introspection
	Duration   time.Duration       `json:"duration"`    // Total introspection time
	Timestamp  time.Time           `json:"timestamp"`   // When introspection was performed
}

// Error types
type OrchestratorError struct {
	Code    string `json:"code"`
	Message string `json:"message"`
	Details string `json:"details"`
}

func (e OrchestratorError) Error() string {
	return e.Message
}

// Common error codes
const (
	ErrorServiceUnavailable       = "SERVICE_UNAVAILABLE"
	ErrorIntrospectionFailed      = "INTROSPECTION_FAILED"
	ErrorWorkflowGenerationFailed = "WORKFLOW_GENERATION_FAILED"
	ErrorWorkflowExecutionFailed  = "WORKFLOW_EXECUTION_FAILED"
	ErrorInvalidRequest           = "INVALID_REQUEST"
	ErrorLLMError                 = "LLM_ERROR"
	ErrorTimeout                  = "TIMEOUT"
)
